# Generated by Django 6.0.9 on 2026-10-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_preset',
            field=models.CharField(blank=True, choices=[('fox', 'Fox'), ('panda', 'Panda'), ('tiger', 'Tiger'), ('frog', 'Frog'), ('lion', 'Lion'), ('koala', 'Koala'), ('octopus', 'Octopus'), ('unicorn', 'Unicorn'), ('penguin', 'Penguin'), ('bear', 'Bear'), ('rabbit', 'Rabbit'), ('owl', 'Owl')], max_length=20),
        ),
    ]
