# Generated by Django 6.0.9 on 2026-10-07 16:25

import django.db.models.deletion
import django.utils.timezone
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File')], default='TEXT', max_length=5)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=messaging.models.image_upload_to)),
                ('video', models.FileField(blank=True, upload_to=messaging.models.video_upload_to)),
                ('audio', models.FileField(blank=True, upload_to=messaging.models.audio_upload_to)),
                ('file', models.FileField(blank=True, upload_to=messaging.models.file_upload_to)),
                ('thumbnail', models.ImageField(blank=True, upload_to=messaging.models.thumbnail_upload_to)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('waveform', models.JSONField(blank=True, null=True)),
                ('preview', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['chat', 'id'], name='messaging_chat_id_idx'), models.Index(condition=models.Q(('is_read', False)), fields=['chat'], name='messaging_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('sender', 'client_id'), name='messaging_sender_client_id_unique')],
            },
        ),
    ]
