import os
import re
import uuid

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone


def _upload_path(folder, filename):
    # Stored names are random: the original name is kept in `file_name` only.
    extension = os.path.splitext(filename)[1].lower()
    if not re.fullmatch(r'\.[a-z0-9]{1,10}', extension):
        extension = ''
    return f'{folder}/{timezone.now():%Y/%m}/{uuid.uuid4().hex}{extension}'


def image_upload_to(instance, filename):
    return _upload_path('images', filename)


def video_upload_to(instance, filename):
    return _upload_path('videos', filename)


def audio_upload_to(instance, filename):
    return _upload_path('audio', filename)


def file_upload_to(instance, filename):
    return _upload_path('files', filename)


def thumbnail_upload_to(instance, filename):
    return _upload_path('thumbnails', filename)


class Message(models.Model):
    class Type(models.TextChoices):
        TEXT = 'TEXT', 'Text'
        IMAGE = 'IMAGE', 'Image'
        VIDEO = 'VIDEO', 'Video'
        AUDIO = 'AUDIO', 'Audio'
        FILE = 'FILE', 'File'

    chat = models.ForeignKey('chats.Chat', on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    type = models.CharField(max_length=5, choices=Type.choices, default=Type.TEXT)
    text = models.TextField(blank=True)  # the message, or the caption of a media message

    image = models.ImageField(upload_to=image_upload_to, blank=True)
    video = models.FileField(upload_to=video_upload_to, blank=True)
    audio = models.FileField(upload_to=audio_upload_to, blank=True)
    file = models.FileField(upload_to=file_upload_to, blank=True)
    thumbnail = models.ImageField(upload_to=thumbnail_upload_to, blank=True)  # video poster frame

    file_name = models.CharField(max_length=255, blank=True)
    file_size = models.PositiveBigIntegerField(null=True, blank=True)
    mime_type = models.CharField(max_length=100, blank=True)
    duration = models.FloatField(null=True, blank=True)  # seconds (audio / video)
    width = models.PositiveIntegerField(null=True, blank=True)
    height = models.PositiveIntegerField(null=True, blank=True)
    waveform = models.JSONField(null=True, blank=True)  # voice message peaks, 0..1
    preview = models.TextField(blank=True)  # tiny blurred data: URI shown while media loads

    reply_to = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='replies')
    is_read = models.BooleanField(default=False)
    # Generated by the sender's app: resending the same message never creates a duplicate.
    client_id = models.UUIDField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    MEDIA_FIELDS = {
        Type.IMAGE: 'image',
        Type.VIDEO: 'video',
        Type.AUDIO: 'audio',
        Type.FILE: 'file',
    }

    class Meta:
        ordering = ['id']
        indexes = [
            models.Index(fields=['chat', 'id'], name='messaging_chat_id_idx'),
            models.Index(fields=['chat'], condition=Q(is_read=False), name='messaging_unread_idx'),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['sender', 'client_id'],
                condition=Q(client_id__isnull=False),
                name='messaging_sender_client_id_unique',
            ),
        ]

    def __str__(self):
        return f'{self.type} message {self.pk} in chat {self.chat_id}'

    @property
    def attachment(self):
        field = self.MEDIA_FIELDS.get(self.type)
        return getattr(self, field) if field else None

    def stored_file_names(self):
        files = (self.image, self.video, self.audio, self.file, self.thumbnail)
        return [stored.name for stored in files if stored]
